apiVersion: v1
kind: Pod
metadata:
  name: feel-tutorial-pod
  labels:
    app: feel-tutorial
spec:
  containers:
    - name: nginx-container
      image: upgradingdave/feel-tutorial:1.0.2
      env:
        - name: ZEEBE_BASE_URL
          valueFrom:
            secretKeyRef:
              name: feel-tutorial
              key: zeebe.client.cloud.base-url
        - name: ZEEBE_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: feel-tutorial
              key: zeebe.client.cloud.auth-url
        - name: ZEEBE_REGION
          valueFrom:
            secretKeyRef:
              name: feel-tutorial
              key: zeebe.client.cloud.region
        - name: ZEEBE_CLUSTER_ID
          valueFrom:
            secretKeyRef:
              name: feel-tutorial
              key: zeebe.client.cloud.clusterId
        - name: ZEEBE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: feel-tutorial
              key: zeebe.client.cloud.clientId
        - name: ZEEBE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: feel-tutorial
              key: zeebe.client.cloud.clientSecret

