
version: '3.8'

volumes:
  certs:

networks:
  camunda-platform: { }

services:
  feel-tutorial:
    container_name: feel-tutorial
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./certs:/opt/certs
    environment:
      PORT: 8080
      ZEEBE_BASE_URL: zeebe.ultrawombat.com
      ZEEBE_AUTH_URL: https://login.cloud.ultrawombat.com/oauth/token
      ZEEBE_REGION: bru-2
      ZEEBE_CLUSTER_ID: 8a992fca-ea6e-4ec6-b5ff-4773fae19d20
      ZEEBE_CLIENT_ID: -JemRlKAjNZRINgPwjrXTUqfKIUcSKkT
      ZEEBE_CLIENT_SECRET: ODkEj77NWUxAr.d2iSIZpLk38O91H~2tJ1NdRNRo-xd3~gRyarrJn0M_xdVdW4kS
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
        reservations:
          memory: 1000M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://feel-tutorial:8080/swatter-ui"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - camunda-platform
